[package]
name = "cosmic-weather"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
open = "5.1.2"
serde = "1.0.197"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["debug", "wayland", "tokio"]
